"""add customer_name to milk_intake

Revision ID: 21d86c5f98bb
Revises: 54118dcf5d5f
Create Date: 2026-02-11 13:42:46.191362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d86c5f98bb'
down_revision: Union[str, Sequence[str], None] = '54118dcf5d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Add column as nullable first
    op.add_column(
        'milk_intake',
        sa.Column('customer_name', sa.String(length=100), nullable=True)
    )

    # 2️⃣ Update existing rows
    op.execute(
        "UPDATE milk_intake SET customer_name = 'Unknown'"
    )

    # 3️⃣ Make column NOT NULL
    op.alter_column(
        'milk_intake',
        'customer_name',
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milk_intake', 'customer_name')
    # ### end Alembic commands ###
